In [31]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns

In [32]:
# Online datasets joylashgan manzilni korsatamiz
url = 'https://github.com/ageron/handson-ml2/blob/master/datasets/housing/housing.csv?raw=true'
df = pd.read_csv(url)
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [33]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(df, test_size=0.2, random_state=45)

In [34]:
housing = train_set.drop('median_house_value', axis=1)
housing_labels = train_set['median_house_value'].copy()

In [35]:
df.info() # df haqida umumiy malumot

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [36]:
# 1-NaN qiymatlari bor qatorlarni tashlab yuborish
housing.dropna(subset=['total_bedrooms'])

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
13240    -117.67     34.12                15.0       3162.0           495.0   
12586    -121.50     38.53                37.0       3642.0           684.0   
13123    -121.26     38.27                20.0       1314.0           229.0   
15456    -117.28     33.18                16.0       3002.0           591.0   
19798    -123.12     40.54                23.0       1091.0           217.0   
...          ...       ...                 ...          ...             ...   
16547    -121.22     37.81                20.0       1811.0           352.0   
16317    -121.32     38.00                22.0       2105.0           521.0   
12895    -121.33     38.65                24.0       3533.0           741.0   
6012     -117.78     34.07                18.0       3610.0           772.0   
6558     -118.11     34.20                36.0       4915.0           725.0   

       population  households  median_income ocean_proximity  
13240      1145.0       473.0         5.3525          INLAND  
12586      1508.0       657.0         3.5231          INLAND  
13123       712.0       219.0         4.4125          INLAND  
15456       842.0       538.0         2.1205      NEAR OCEAN  
19798       539.0       201.0         1.8696          INLAND  
...           ...         ...            ...             ...  
16547      1191.0       327.0         4.0125          INLAND  
16317       781.0       483.0         2.2130          INLAND  
12895      1496.0       723.0         2.8106          INLAND  
6012       2899.0       765.0         3.9784          INLAND  
6558       1897.0       700.0         6.8270          INLAND  

[16356 rows x 9 columns]

In [37]:
# 2-Ustunlarni tashlab yuborish
housing.drop('total_bedrooms', axis=1)

longitude  latitude  housing_median_age  total_rooms  population  \
13240    -117.67     34.12                15.0       3162.0      1145.0   
12586    -121.50     38.53                37.0       3642.0      1508.0   
13123    -121.26     38.27                20.0       1314.0       712.0   
15456    -117.28     33.18                16.0       3002.0       842.0   
19798    -123.12     40.54                23.0       1091.0       539.0   
...          ...       ...                 ...          ...         ...   
16547    -121.22     37.81                20.0       1811.0      1191.0   
16317    -121.32     38.00                22.0       2105.0       781.0   
12895    -121.33     38.65                24.0       3533.0      1496.0   
6012     -117.78     34.07                18.0       3610.0      2899.0   
6558     -118.11     34.20                36.0       4915.0      1897.0   

       households  median_income ocean_proximity  
13240       473.0         5.3525          INLAND  
12586       657.0         3.5231          INLAND  
13123       219.0         4.4125          INLAND  
15456       538.0         2.1205      NEAR OCEAN  
19798       201.0         1.8696          INLAND  
...           ...            ...             ...  
16547       327.0         4.0125          INLAND  
16317       483.0         2.2130          INLAND  
12895       723.0         2.8106          INLAND  
6012        765.0         3.9784          INLAND  
6558        700.0         6.8270          INLAND  

[16512 rows x 8 columns]

In [38]:
#  3- NaN qiymatlarni boshqa qiymatlar bilan almashtirish
median = housing['total_bedrooms'].median()
median

435.0

In [39]:
housing['total_bedrooms'].fillna(median)

13240    495.0
12586    684.0
13123    229.0
15456    591.0
19798    217.0
         ...  
16547    352.0
16317    521.0
12895    741.0
6012     772.0
6558     725.0
Name: total_bedrooms, Length: 16512, dtype: float64

# SimleImputer

In [40]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='median')

In [41]:
# bunda faqat raqamlar bilan ishlayshimiz munkun yani starategiyaga bog`liq
# imputer.fit(housing)

In [42]:
housing_num = housing.drop('ocean_proximity', axis=1)
housing_num

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
13240    -117.67     34.12                15.0       3162.0           495.0   
12586    -121.50     38.53                37.0       3642.0           684.0   
13123    -121.26     38.27                20.0       1314.0           229.0   
15456    -117.28     33.18                16.0       3002.0           591.0   
19798    -123.12     40.54                23.0       1091.0           217.0   
...          ...       ...                 ...          ...             ...   
16547    -121.22     37.81                20.0       1811.0           352.0   
16317    -121.32     38.00                22.0       2105.0           521.0   
12895    -121.33     38.65                24.0       3533.0           741.0   
6012     -117.78     34.07                18.0       3610.0           772.0   
6558     -118.11     34.20                36.0       4915.0           725.0   

       population  households  median_income  
13240      1145.0       473.0         5.3525  
12586      1508.0       657.0         3.5231  
13123       712.0       219.0         4.4125  
15456       842.0       538.0         2.1205  
19798       539.0       201.0         1.8696  
...           ...         ...            ...  
16547      1191.0       327.0         4.0125  
16317       781.0       483.0         2.2130  
12895      1496.0       723.0         2.8106  
6012       2899.0       765.0         3.9784  
6558       1897.0       700.0         6.8270  

[16512 rows x 8 columns]

In [43]:
imputer.fit(housing_num)

SimpleImputer(strategy='median')

In [44]:
imputer.statistics_

array([-118.48  ,   34.25  ,   29.    , 2127.    ,  435.    , 1167.    ,
        409.    ,    3.5313])

In [45]:
x = imputer.transform(housing_num) # bunda bizga yangi array qaytaradi
x

array([[-1.1767e+02,  3.4120e+01,  1.5000e+01, ...,  1.1450e+03,
         4.7300e+02,  5.3525e+00],
       [-1.2150e+02,  3.8530e+01,  3.7000e+01, ...,  1.5080e+03,
         6.5700e+02,  3.5231e+00],
       [-1.2126e+02,  3.8270e+01,  2.0000e+01, ...,  7.1200e+02,
         2.1900e+02,  4.4125e+00],
       ...,
       [-1.2133e+02,  3.8650e+01,  2.4000e+01, ...,  1.4960e+03,
         7.2300e+02,  2.8106e+00],
       [-1.1778e+02,  3.4070e+01,  1.8000e+01, ...,  2.8990e+03,
         7.6500e+02,  3.9784e+00],
       [-1.1811e+02,  3.4200e+01,  3.6000e+01, ...,  1.8970e+03,
         7.0000e+02,  6.8270e+00]])

In [46]:
x = imputer.fit_transform(housing_num) # fit va transform ni birgalikda ishlatishimiz munkun
x

array([[-1.1767e+02,  3.4120e+01,  1.5000e+01, ...,  1.1450e+03,
         4.7300e+02,  5.3525e+00],
       [-1.2150e+02,  3.8530e+01,  3.7000e+01, ...,  1.5080e+03,
         6.5700e+02,  3.5231e+00],
       [-1.2126e+02,  3.8270e+01,  2.0000e+01, ...,  7.1200e+02,
         2.1900e+02,  4.4125e+00],
       ...,
       [-1.2133e+02,  3.8650e+01,  2.4000e+01, ...,  1.4960e+03,
         7.2300e+02,  2.8106e+00],
       [-1.1778e+02,  3.4070e+01,  1.8000e+01, ...,  2.8990e+03,
         7.6500e+02,  3.9784e+00],
       [-1.1811e+02,  3.4200e+01,  3.6000e+01, ...,  1.8970e+03,
         7.0000e+02,  6.8270e+00]])

In [47]:
housing_tr = pd.DataFrame(x, columns=housing_num.columns, index=housing_num.index)
housing_tr

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
13240    -117.67     34.12                15.0       3162.0           495.0   
12586    -121.50     38.53                37.0       3642.0           684.0   
13123    -121.26     38.27                20.0       1314.0           229.0   
15456    -117.28     33.18                16.0       3002.0           591.0   
19798    -123.12     40.54                23.0       1091.0           217.0   
...          ...       ...                 ...          ...             ...   
16547    -121.22     37.81                20.0       1811.0           352.0   
16317    -121.32     38.00                22.0       2105.0           521.0   
12895    -121.33     38.65                24.0       3533.0           741.0   
6012     -117.78     34.07                18.0       3610.0           772.0   
6558     -118.11     34.20                36.0       4915.0           725.0   

       population  households  median_income  
13240      1145.0       473.0         5.3525  
12586      1508.0       657.0         3.5231  
13123       712.0       219.0         4.4125  
15456       842.0       538.0         2.1205  
19798       539.0       201.0         1.8696  
...           ...         ...            ...  
16547      1191.0       327.0         4.0125  
16317       781.0       483.0         2.2130  
12895      1496.0       723.0         2.8106  
6012       2899.0       765.0         3.9784  
6558       1897.0       700.0         6.8270  

[16512 rows x 8 columns]

In [48]:
housing_cat = housing[['ocean_proximity']]
housing_cat.value_counts()

ocean_proximity
<1H OCEAN          7285
INLAND             5261
NEAR OCEAN         2115
NEAR BAY           1848
ISLAND                3
dtype: int64

In [49]:
from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder = OrdinalEncoder()

housing_cat_encoded = ordinal_encoder.fit_transform(housing_cat)
housing_cat_encoded

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]])

# 2- usul matnlar bilan ishlashni

In [50]:
from sklearn.preprocessing import OneHotEncoder

cat_encoder = OneHotEncoder()

housing_cat_1hot = cat_encoder.fit_transform(housing_cat)
housing_cat_1hot.toarray()

array([[0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       ...,
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

# yangi bir transform yasaymiz

In [51]:
from sklearn.base import BaseEstimator, TransformerMixin

# bizga kerak ustunlar indekslari
rooms_ix, bedrooms_ix, population_ix, households_ix = 3, 4, 5, 6

class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
    def __init__(self, add_bedrooms_per_room = True):
        self.add_bedrooms_per_room = add_bedrooms_per_room
    def fit(self, X, y=None):
        return self # bizni funksiyamiz faqat transformer. estimator emas
    def transform(self, X):
        rooms_per_household = X[:, rooms_ix] / X[:, households_ix]
        population_per_household = X[:, population_ix] / X[:, households_ix]
        if self.add_bedrooms_per_room: # add_bedrooms_per_room ustuni ixtiyoriy bo'ladi
            bedrooms_per_room = X[:, bedrooms_ix] / X[:, rooms_ix]
            return np.c_[X, rooms_per_household, population_per_household, bedrooms_per_room]
        else:
            return np.c_[X, rooms_per_household, population_per_household]

In [52]:
attr_adder = CombinedAttributesAdder()
housing_extra_attribs = attr_adder.transform(housing.values)
housing_extra_attribs

array([[-117.67, 34.12, 15.0, ..., 6.6849894291754755,
        2.4207188160676534, 0.15654648956356737],
       [-121.5, 38.53, 37.0, ..., 5.54337899543379, 2.295281582952816,
        0.18780889621087316],
       [-121.26, 38.27, 20.0, ..., 6.0, 3.2511415525114153,
        0.17427701674277016],
       ...,
       [-121.33, 38.65, 24.0, ..., 4.8865836791148, 2.0691562932226835,
        0.20973676761958676],
       [-117.78, 34.07, 18.0, ..., 4.718954248366013, 3.7895424836601306,
        0.21385041551246536],
       [-118.11, 34.2, 36.0, ..., 7.021428571428571, 2.71,
        0.14750762970498474]], dtype=object)

In [53]:
housing.values[0]

array([-117.67, 34.12, 15.0, 3162.0, 495.0, 1145.0, 473.0, 5.3525,
       'INLAND'], dtype=object)

In [54]:
housing_extra_attribs[0]

array([-117.67, 34.12, 15.0, 3162.0, 495.0, 1145.0, 473.0, 5.3525,
       'INLAND', 6.6849894291754755, 2.4207188160676534,
       0.15654648956356737], dtype=object)

In [55]:
housing.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
13240    -117.67     34.12                15.0       3162.0           495.0   
12586    -121.50     38.53                37.0       3642.0           684.0   
13123    -121.26     38.27                20.0       1314.0           229.0   
15456    -117.28     33.18                16.0       3002.0           591.0   
19798    -123.12     40.54                23.0       1091.0           217.0   

       population  households  median_income ocean_proximity  
13240      1145.0       473.0         5.3525          INLAND  
12586      1508.0       657.0         3.5231          INLAND  
13123       712.0       219.0         4.4125          INLAND  
15456       842.0       538.0         2.1205      NEAR OCEAN  
19798       539.0       201.0         1.8696          INLAND

In [56]:
housing.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  16512.000000  16512.000000        16512.000000  16512.000000   
mean    -119.560076     35.625683           28.681141   2633.885598   
std        2.002634      2.136307           12.596014   2193.610901   
min     -124.300000     32.540000            1.000000      6.000000   
25%     -121.790000     33.930000           18.000000   1448.750000   
50%     -118.480000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.710000           37.000000   3131.250000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  
count    16356.000000  16512.000000  16512.000000   16512.000000  
mean       538.122096   1422.223110    499.093932       3.865637  
std        421.863076   1108.809799    381.632718       1.905095  
min          1.000000      3.000000      1.000000       0.499900  
25%        296.000000    788.000000    280.000000       2.558600  
50%        435.000000   1167.000000    409.000000       3.531300  
75%        646.000000   1725.000000    602.000000       4.734400  
max       6445.000000  28566.000000   6082.000000      15.000100

# min max skerlir malum bir oraliqa tushirib olish

In [58]:
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()

min_max_scaler.fit_transform(housing_num)

array([[0.66366366, 0.16790648, 0.2745098 , ..., 0.03998179, 0.07761881,
        0.33465745],
       [0.28028028, 0.63655685, 0.70588235, ..., 0.05269054, 0.10787699,
        0.20849368],
       [0.3043043 , 0.60892667, 0.37254902, ..., 0.02482232, 0.03584937,
        0.26983076],
       ...,
       [0.2972973 , 0.64930925, 0.45098039, ..., 0.05227042, 0.11873047,
        0.15935642],
       [0.65265265, 0.16259299, 0.33333333, ..., 0.10138991, 0.12563723,
        0.23989324],
       [0.61961962, 0.17640808, 0.68627451, ..., 0.06630956, 0.1149482 ,
        0.43634571]])

In [59]:
housing_num

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
13240    -117.67     34.12                15.0       3162.0           495.0   
12586    -121.50     38.53                37.0       3642.0           684.0   
13123    -121.26     38.27                20.0       1314.0           229.0   
15456    -117.28     33.18                16.0       3002.0           591.0   
19798    -123.12     40.54                23.0       1091.0           217.0   
...          ...       ...                 ...          ...             ...   
16547    -121.22     37.81                20.0       1811.0           352.0   
16317    -121.32     38.00                22.0       2105.0           521.0   
12895    -121.33     38.65                24.0       3533.0           741.0   
6012     -117.78     34.07                18.0       3610.0           772.0   
6558     -118.11     34.20                36.0       4915.0           725.0   

       population  households  median_income  
13240      1145.0       473.0         5.3525  
12586      1508.0       657.0         3.5231  
13123       712.0       219.0         4.4125  
15456       842.0       538.0         2.1205  
19798       539.0       201.0         1.8696  
...           ...         ...            ...  
16547      1191.0       327.0         4.0125  
16317       781.0       483.0         2.2130  
12895      1496.0       723.0         2.8106  
6012       2899.0       765.0         3.9784  
6558       1897.0       700.0         6.8270  

[16512 rows x 8 columns]

# Standartizatsiya

In [60]:
from sklearn.preprocessing import StandardScaler

standart_scaler = StandardScaler()

standart_scaler.fit_transform(housing_num)

array([[ 0.94382381, -0.70482757, -1.08618132, ..., -0.2500262 ,
        -0.06837653,  0.78049   ],
       [-0.96871548,  1.35954492,  0.66045582, ...,  0.07736177,
         0.41377702, -0.17980607],
       [-0.84886968,  1.23783588, -0.68921833, ..., -0.64054684,
        -0.73395807,  0.28706138],
       ...,
       [-0.8838247 ,  1.41571832, -0.37164794, ...,  0.06653903,
         0.58672341, -0.55381447],
       [ 0.88889449, -0.72823316, -0.84800353, ...,  1.33189805,
         0.6967802 ,  0.05919185],
       [ 0.72410651, -0.66737864,  0.58106323, ...,  0.42819902,
         0.52645421,  1.55449053]])